### ISSUE TITLE
onNext() get called during RxLoader creation

### ISSUE THREAD

**Issue by huahou** [evant/rxloader#15]
I have a fragment hosted by an activity. Within the fragment, I create an RxLoader by:

RxLoader1<DealSavable, MyData> myLoader;

myLoader = RxLoaderManager.get(getActivity()).create(..., new RxLoaderObserver<MyData>() {
                    @Override
                    public void onNext(MyData value) {
                    }
                    ...
                 });

myLoader.restart();

The problem is: If the loader retrieved some data, and after that, if the activity is re-created, during the above "create()" method call, the onNext() is called immediately with previously loaded stale data. 

Is this a bug? How can I make sure that onNext() is called only when "restart()" is called?

**Comment by evant** [comment]
This is by design. Normally you'd want to use the previous result to recreate your ui state after an orientation change.

**Comment by huahou** [comment]
Thanks for the feedback. Is there a way to override this default behavior?

**Comment by evant** [comment]
Not really, if you have some transient state, you could store a flag that determines if you've handled it I guess. I haven't really thought about a good api for that.

**Comment by evant** [comment]
I've actually run into this issue myself, (I was showing an error toast and I didn't want it to show again after you rotated), maybe a loader.clear() method would be good solution.

**Comment by huahou** [comment]
Neither RxLoader nor RxLoaderManager have "clear()" method. Which "clear()" method are you referring to?

**Comment by evant** [comment]
Sorry, maybe I wasn't clear enough. I'm thinking out-loud about a future api to solve this issue. I thought maybe there could be a clear() method on RxLoader that would clear the cached value if you no longer want to get it on configuration changes.

**Comment by huahou** [comment]
that will definitely help.

**Comment by huahou** [comment]
Thank you for the quick fix! really appreciate!

**Comment by evant** [comment]
I want to keep this open until a I actually release a new version to maven central.
