### ISSUE TITLE
Example won't run due to gradle issue

### ISSUE THREAD

**Issue by kuriandungu** [evant/rxloader#20]
I've cloned the example on my pc but i'm unable to run it due to a couple of gradle errors. specifically
1."Error:(21, 14) Failed to resolve: android:android:4.3_r2"  
2. "Error:(22, 14) Failed to resolve: android.support:compatibility-v4:21.0.0"

For error one i couldn't find android 4.3_r2 listed in the sdk although i have all of them installed till ver 24.2
For error 2, being a newbie , i've no clue what the issue is.
Thanks.

**Comment by evant** [comment]
Sorry, should have mentioned it in the REAME, but you need to run https://github.com/simpligility/maven-android-sdk-deployer. This is because it's packaged as a jar instead of an aar and so it can't use the android plugin to point to your sdks normally.

**Comment by kuriandungu** [comment]
Thanks for the quick reply. at the moment i'm completely lost on how to integrate with the deployer etc but i'll figure it out.

**Comment by kuriandungu** [comment]
Hello Evant,

I’d like to appreciate your work and effort by saying a big Thank you! 

I’m using Retrolambda which is one of your libraries and it’s been great.

 

I just thought that perhaps guys consume your products but may be too busy to really appreciate. So thanks again for the Genius level code. Its making a difference to guys as far as Nairobi!

 

Cheers.

**Comment by evant** [comment]
Also, if you are just want to run the sample project without building rxloader, you can simply remove `':rxloader'` from settings.gradle and change `project(':rxloader')` to `compile 'me.tatarka.rxloader:rxloader:1.1.0'''` in sample/build.gradle

**Comment by kuriandungu** [comment]
Asante Sana! (Thank you very much) - I'm now able to run the sample!
