### ISSUE TITLE
Create loader not in onCreate() method

### ISSUE THREAD

**Issue by nesterov-n** [evant/rxloader#24]
Documentation for all `RxLoaderManager#create` methods contains requirement:
> This should be called in Activity.onCreate(android.os.Bundle) or similar.

Is it totally impossible to create loader not in `onCreate` method (for example, create loader to upload photos selected by user) and make this loader persistable across activity configuration changes?

**Comment by evant** [comment]
You can create a loader that you can pass argument to. See the example i the README or the sample app.

**Comment by nesterov-n** [comment]
Thanks, yes. I understand your example. But my case is bit more complicated. User can add multiple photos. So I need multiple loaders and they should work in parallel. Is possible to create loaders on demand, not only in `onCreate()` method?

**Comment by evant** [comment]
Well, you can do that. You just need to make sure to re-attach any loaders in flight in `onCreate` after a configuration change. You'll have to do that bookkeeping yourself.

**Comment by nesterov-n** [comment]
Many thanks for help!
